-- Raw SQL constraints Prisma cannot express in schema.prisma.
--
-- These statements MUST be appended to the migration.sql of the FIRST
-- migration generated by `prisma migrate dev` (see packages/db/README.md).
-- They are written to be idempotent so re-application is harmless.

-- ---------------------------------------------------------------------------
-- Overbooking is impossible at the DB level (invariant #3 in CLAUDE.md).
-- App code books via conditional UPDATE ... WHERE booked_seats + n <= capacity;
-- this CHECK is the backstop.
-- ---------------------------------------------------------------------------
ALTER TABLE "sessions"
  DROP CONSTRAINT IF EXISTS "sessions_booked_seats_within_capacity";
ALTER TABLE "sessions"
  ADD CONSTRAINT "sessions_booked_seats_within_capacity"
  CHECK ("booked_seats" >= 0 AND "booked_seats" <= "capacity");

-- ---------------------------------------------------------------------------
-- Brand-wide discount codes (location_id IS NULL) must be unique. Postgres
-- treats NULLs as distinct in the @@unique([locationId, code]) constraint, so
-- brand-wide uniqueness needs a partial unique index (case-insensitive).
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS "discount_codes_brand_wide_code_key"
  ON "discount_codes" (lower("code"))
  WHERE "location_id" IS NULL;

-- ---------------------------------------------------------------------------
-- Same NULL-distinctness caveat for org-wide staff roles (location_id IS NULL,
-- e.g. CORPORATE_ADMIN): prevent duplicate global role rows per staff user.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS "staff_roles_global_role_key"
  ON "staff_roles" ("staff_user_id", "role")
  WHERE "location_id" IS NULL;

-- ---------------------------------------------------------------------------
-- Discount codes must carry the value field matching their type.
-- ---------------------------------------------------------------------------
ALTER TABLE "discount_codes"
  DROP CONSTRAINT IF EXISTS "discount_codes_value_matches_type";
ALTER TABLE "discount_codes"
  ADD CONSTRAINT "discount_codes_value_matches_type"
  CHECK (
    ("type" = 'PERCENT' AND "value_bps" IS NOT NULL)
    OR ("type" = 'FIXED_CENTS' AND "value_cents" IS NOT NULL)
  );

-- ---------------------------------------------------------------------------
-- Stored-value ledger rows must move something and point at something.
-- ---------------------------------------------------------------------------
ALTER TABLE "stored_value_ledger"
  DROP CONSTRAINT IF EXISTS "stored_value_ledger_has_delta";
ALTER TABLE "stored_value_ledger"
  ADD CONSTRAINT "stored_value_ledger_has_delta"
  CHECK ("delta_cents" IS NOT NULL OR "delta_credits" IS NOT NULL);

ALTER TABLE "stored_value_ledger"
  DROP CONSTRAINT IF EXISTS "stored_value_ledger_has_target";
ALTER TABLE "stored_value_ledger"
  ADD CONSTRAINT "stored_value_ledger_has_target"
  CHECK (
    "gift_card_id" IS NOT NULL
    OR "pack_balance_id" IS NOT NULL
    OR "customer_id" IS NOT NULL
  );

-- ---------------------------------------------------------------------------
-- EXCLUSIVE sessions must reference the buyout booking that claimed them.
-- ---------------------------------------------------------------------------
ALTER TABLE "sessions"
  DROP CONSTRAINT IF EXISTS "sessions_exclusive_requires_booking";
ALTER TABLE "sessions"
  ADD CONSTRAINT "sessions_exclusive_requires_booking"
  CHECK ("status" <> 'EXCLUSIVE' OR "exclusive_booking_id" IS NOT NULL);

-- ---------------------------------------------------------------------------
-- Bookings always hold at least one seat.
-- ---------------------------------------------------------------------------
ALTER TABLE "bookings"
  DROP CONSTRAINT IF EXISTS "bookings_seats_positive";
ALTER TABLE "bookings"
  ADD CONSTRAINT "bookings_seats_positive"
  CHECK ("seats" >= 1);
